# Generated by Django 4.2.23 on 2025-08-11 21:16

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="QSO",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("callsign", models.CharField(db_index=True, max_length=32)),
                ("qso_date", models.DateField(help_text="Date of QSO (UTC)")),
                ("time_on", models.TimeField(help_text="Start time (UTC)")),
                ("band", models.CharField(help_text="Band, e.g., 20m", max_length=16)),
                (
                    "mode",
                    models.CharField(help_text="Mode, e.g., SSB, FT8", max_length=32),
                ),
                ("rst_sent", models.CharField(blank=True, max_length=8)),
                ("rst_rcvd", models.CharField(blank=True, max_length=8)),
                (
                    "freq",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=10, null=True
                    ),
                ),
                ("country", models.CharField(blank=True, max_length=64)),
                ("gridsquare", models.CharField(blank=True, max_length=16)),
                ("comment", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["-qso_date", "-time_on", "callsign"],
            },
        ),
    ]
