# Generated by Django 4.2.23 on 2025-08-11 21:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("qsos", "0002_lotw_fields"),
    ]

    operations = [
        migrations.AlterField(
            model_name="qso",
            name="gridsquare",
            field=models.CharField(
                blank=True, help_text="Grid (worked station)", max_length=16
            ),
        ),
    ]
