# Generated by Django 5.0.14 on 2025-08-11 19:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Upload",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="QSO",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("call", models.CharField(max_length=32)),
                ("station_callsign", models.CharField(max_length=32)),
                ("qso_date", models.DateField(blank=True, null=True)),
                ("time_on", models.TimeField(blank=True, null=True)),
                ("band", models.CharField(blank=True, max_length=16)),
                ("mode", models.CharField(blank=True, max_length=16)),
                (
                    "upload",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="qsos",
                        to="logbook.upload",
                    ),
                ),
            ],
        ),
    ]
