# Generated by Django 5.0.14 on 2025-08-11 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("logbook", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="qso",
            name="freq",
            field=models.DecimalField(
                blank=True, decimal_places=6, max_digits=10, null=True
            ),
        ),
    ]
