name: CI

on:
  push:
  pull_request:

jobs:
  lint-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install fastapi uvicorn sqlalchemy requests pydantic pytest flake8

      - name: Install Node dependencies
        if: ${{ hashFiles('package.json') != '' }}
        run: npm ci

      - name: Run flake8
        run: flake8

      - name: Run tests
        run: pytest -q
