name: CI

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Install Node dependencies
        run: |
          if [ -f package-lock.json ] || [ -f package.json ]; then npm ci; fi

      - name: Run flake8
        run: |
          if command -v flake8; then flake8 .; fi

      - name: Run eslint
        run: |
          if [ -f package.json ]; then npx eslint .; fi

      - name: Run tests
        run: |
          if command -v pytest; then pytest -q; fi
